### ISSUE TITLE
table_page.GetRecordCount() 函数未实现预期结果

### ISSUE THREAD

**Issue by zuobiao-zhou** [thu-db/huadb#2]
我的理解是 `table_page.GetRecordCount()` 的作用是获取该页面上的记录数量。比如若该页面上无记录，则返回0；插入了一条记录后，则返回1.
当前函数实现为 `return (*lower_ - PAGE_HEADER_SIZE + 24) / sizeof(Slot);` 但是 `sizeof(Slot)` 固定为4，无法实现预期结果
![image](https://github.com/thu-db/huadb/assets/61108539/54e89693-6815-4280-8eb8-0b6942755b75)
我将其修改为
```
db_size_t count = 0;
db_size_t lower_temp = *lower_;
while (lower_temp > PAGE_HEADER_SIZE){
  lower_temp -= slots_[count].size_;
  count++;
}
return count;
```
可以实现预期结果

**Comment by zuobiao-zhou** [comment]
函数实现没有问题，是我理解错了，page_data前面放的是slots_数组，后面是record

**Comment by hnjylwb** [comment]
感谢反馈，我们根据你的反馈在文档中增加了页面组织示意图
