### ISSUE TITLE
关于命令make labn-only的问题

### ISSUE THREAD

**Issue by momona06** [thu-db/huadb#9]
![WechatIMG854](https://github.com/thu-db/huadb/assets/93273462/d6b58667-8e5a-4bc3-b270-bcabefe146b5)
Makefile中将lab%置于lab%-only之前，会导致labn-only命令匹配labn的命令造成错误
<img width="373" alt="a" src="https://github.com/thu-db/huadb/assets/93273462/e110f309-259c-487c-aa02-ee07f3112c58">

**Comment by hnjylwb** [comment]
经检查，GNU Make 于 3.82 版本引入了 shortest stem 匹配规则，使用 3.82 及之后的版本不会出现该问题。3.81 及之前的 make 版本（如 macOS 自带的 make 为 3.81 版本）采用的是 first match 匹配，会导致 make lab1-only 出现匹配错误。感谢你的反馈，我们会在更新中修复该错误。
